### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by daattaa** [zone117x/node-scrypt-jane-hash#1]
I am getting an error when installing with npm:

```
node-gyp rebuild

  CXX(target) Release/obj.target/scryptjanehash/scryptjanehash.o
  CC(target) Release/obj.target/scryptjanehash/scrypt-jane.o
In file included from ../scrypt-jane.c:13:
../code/scrypt-jane-test-vectors.h:9:4: warning: missing field 'salt' initializer [-Wmissing-field-initializers]
        {0}
          ^
../scrypt-jane.c:30:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^
1 warning and 1 error generated.
```

I have tried installing on OSX and Centos. Are there any dependencies?

**Comment by zone117x** [comment]
Looks like on OSX you might need to change the malloc include statement. http://bitcoin.stackexchange.com/questions/22239/cudaminer-on-mac-os-x-installation-error-malloc-h-no-such-file-or-directory

It should just work on linux and windows though.

**Comment by daattaa** [comment]
Thanks! I am looking forward to developing 

On my Mac, I made the suggested change and am now getting errors similar to this issue: https://github.com/floodyberry/scrypt-jane/issues/4. I was able to verify by installing scrypt-jane with the "-no-integrated-as" flag.

On linux I am getting gyp rebuild errors for scrypt265 and scrypt-jane.

```
> scrypt256-hash@0.0.3 install node_modules/scrypt256-hash
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/bin/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/usr/lib/python2.6/site-packages/gyp/__init__.py", line 462, in main
    options.circular_check)
  File "/usr/lib/python2.6/site-packages/gyp/__init__.py", line 100, in Load
    depth, generator_input_info, check, circular_check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 2255, in Load
    depth, check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 362, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 217, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 2.6.32-431.5.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

I had to clone the other dependency hash function into my node_modules directory and run `npm install` for them to build correctly. Any suggestions? Do you need any more info?
